#!/bin/sh
# This file is automatically generated by internetIncome.ps1
# It contains commands to be executed inside the tun2socks container

# Commands will be written here dynamically by the PowerShell script 